name: DESKTOP tests via BrowserStack

on:
#  pull_request:
#    branches:
#      - main
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-tests:
    name: 'Run tests on BrowserStack'
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_CONFIG_FILE: browserstack-desktop.yml

    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Write browserstack-desktop.yml from secret
        env:
          CONFIG_BS: ${{ secrets.BROWSERSTACK_DESKTOP }}
        run: |
          echo "$CONFIG_BS" > browserstack-desktop.yml

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Install dependencies
        run: mvn -B -q -DskipTests package

      - name: Run Desktop suite on BrowserStack
        run: mvn clean test -Pdesktop-test -Dset.resolution=desktop

      - name: Attach screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: desktop
          path: ${{ github.workspace }}/screenshots/desktop